### ISSUE TITLE
Not working with laminas/laminas-eventmanager:3.4

### ISSUE THREAD

**Issue by fezfez** [laminas/laminas-cache-storage-adapter-filesystem#25]
Hello,

I've update to ^2.0 but a got an issue

````
aminas\EventManager\EventManager::detach(): Argument #1 ($listener) must be of type callable, null given, called in /var/www/vendor/laminas/laminas-cache-storage-adapter-filesystem/src/Filesystem.php on line 115
````

The $listerne var is null instead of being a callable, see :

(https://github.com/laminas/laminas-cache-storage-adapter-filesystem/blob/ad9d9d19abcdd36c8ccad370120cf5a97a610f80/src/Filesystem.php#L107-L117)

EventManagerInterface : 

https://github.com/laminas/laminas-eventmanager/blob/9e11e32de9eb66451ddaba81d282cccb9bbf245f/src/EventManagerInterface.php#L96-L106

**Comment by boesing** [comment]
Closed with #26
