### ISSUE TITLE
PHP 8.3 Support required...

### ISSUE THREAD

**Issue by nusphere** [laminas/laminas-cache-storage-adapter-filesystem#80]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes

#### Summary
@boesing when will PHP 8.3 support be available in this package? 

Actually the most packages uses the filesystem Adapter. This is the reason why the most applications are have a hard dependency to this package.

This results into a high prio for this package... Or I am wrong...

Br 
Nusphere

**Comment by Ocramius** [comment]
Meh, "high priority" would be a security issue, but what's done here is in good faith, and when possible.

**Comment by Xerkus** [comment]
Resolved
