### ISSUE TITLE
Add a file_user and file_group option to Filesystem Adapter

### ISSUE THREAD

**Issue by smhg** [laminas/laminas-cache-storage-adapter-filesystem#82]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | yes
| BC Break    | no

#### Summary

I use Laminas\Cache\Storage\Adapter\FileSystem. It creates/accesses cache files from webserver requests (Apache) and from cron jobs. These run under different users which are not in the same group. That leads to an error when writing a file created by the other.
I think it would be nice to be able to specify as which user/group (chown) the cache files should be created.
Can I submit a PR to add this option? Or am I approaching this the wrong way?

**Comment by Ocramius** [comment]
IMO that complicates things massively: this is to be handled by you managing processes on your deployment, rather than modifying application (or even library) code.

**Comment by Xerkus** [comment]
This belongs to filesystem adapter repository. Transferring.

**Comment by Xerkus** [comment]
I agree this is better handled differently. But feature itself would be useful as an escape hatch, imo.

**Comment by smhg** [comment]
I've solved this by specifying the user in the cron config. I agree it's not great to put it in the cache config.
I can imagine however a one-time manual execution of the same process by a regular user causes the same issue. Not sure how to handle that.

**Comment by boesing** [comment]
AFAIK, you can configure both file and group permissions via options:

https://github.com/laminas/laminas-cache-storage-adapter-filesystem/blob/924a6ab5f760aa83576e600a83bb7d93d0b15ee6/src/FilesystemOptions.php#L51

https://github.com/laminas/laminas-cache-storage-adapter-filesystem/blob/924a6ab5f760aa83576e600a83bb7d93d0b15ee6/src/FilesystemOptions.php#L63

Put both users meant to execute the application into the same group and adapt the permissions accordingly. Thats at least what I would try to do if there has to be a dedicated cronjob user for whatever reason.

----

I mean, once you mess up permissions, you have a problem. There is nothing you can do about it. Usually, in production, it is recommended to use the error handler plugin to "ignore" errors like these. AFAIK, that just ends up returning `null` from the `StorageInterface#getItem` method.

**Comment by smhg** [comment]
Thank you for the feedback all! I guess there are enough ways around this to not add these options.

FWIW: this popped up when refactoring a Zend Framework 1 project and replacing its Zend_Cache with Laminas\Cache. Somehow this wasn't an issue in the ZF1 setup. Possibly cache files just never got created by the cron job.
