### ISSUE TITLE
Link in README goes 404

### ISSUE THREAD

**Issue by modir** [laminas/laminas-cache-storage-adapter-filesystem#87]
In the README is a link to the documentation. But this link is going only to a 404 page. Maybe someone knows the new location and create a pull request.

**Comment by froschdesign** [comment]
https://docs.laminas.dev/laminas-cache/v3/storage/adapter/#filesystem-adapter

**Comment by modir** [comment]
I made a pull request with the new link. Maybe you want to add more content.

**Comment by boesing** [comment]
Fixed with #88
